### ISSUE TITLE
Putting qp on PyPi

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/qp#26]
I've had some issues getting qp to install properly in setup.py and in certain situations while trying to pip install in GitHub workflows.  I mentioned this to Alex, and we were wondering if getting a release version of qp onto PyPi would both alleviate some of these problems and make it easier to do installs for what will probably be an increasing user base for qp in the near future.
There is an existing (ancient python 2 last updated in 2008) package named qp already on PyPi, so we would probably have to call it desc-qp or something similar.

**Comment by aimalz** [comment]
For PyPi, I'd sort of like to call it something like `qp-for-pdfs` or `qp-probability`, or something like that, since it's generically useful beyond DESC and would be easier to find with a descriptive name. Since we already have a couple tagged releases, we could indeed set that up now to resolve the GitHub workflows bug.

(Also, I've been thinking that we should put together a software paper (maybe for [JOSS](https://joss.theoj.org/)? unless we combine it with a paper for [qit](https://github.com/LSSTDESC/qit), in which case I think MNRAS/AJ might take it) in preparation for a v1.0 release. I guess this is a reminder to make a new issue, and Confluence page, for that. . .)

**Comment by aimalz** [comment]
Oh, another related thing that maybe should be another issue, we need some user-facing documentation, like on readthedocs or something.

**Comment by eacharles** [comment]
qp-pdf?
