### ISSUE TITLE
stability of the mixmod fit

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/qp#28]
I just noticed that the mixmod fitting seems a bit unstable : if you execute several times the part of the code snippet below where the mixmod is created and plotted against the original pdf, you can see that it moves around a bit (I see it on my laptop using a notebook)

```
ens = qp.read('qp_test_ensemble.hdf5')
ens_red = ens[np.arange(10)]
z = ens.metadata()['xvals'][0]
P = ens_red.objdata()['yvals']
Ntot = len(P)
ncomps = 3
xvals = np.linspace(0, 3.0, 301)
#re execute several times the following and see the mixmod pdf plot move around a bit
ens_m = qp.convert(ens_red, 'mixmod', xvals=xvals, ncomps=ncomps)
key = 1
axes_m = ens_red.plot(key, xlim=(0, 0.3), label="original", marker='.')
_ = ens_m.plot(key, axes=axes_m, label="gaus")
leg_m = axes_m.figure.legend()
```

**Comment by eacharles** [comment]
Don't really know what to say, a set of Gaussian with no additional constraints is by definition a pretty degenerate basis set.    

We could disable the fit, or let people figure out on their own that this is not really the cleverest thing to be doing.  But it doesn't seem worth the effort to try and be extra clever and make the fits always converge.

**Comment by drewoldag** [comment]
The heart of this problem lies in the fact that the conversion function relies on random variates being generated in the `extract_mixmod_fit_samples` function [here](https://github.com/LSSTDESC/qp/blob/main/src/qp/conversion_funcs.py#L217) (specifically line 217). 

One naive approach is to modify the `qp.convert(...)` call that you have above from:
`ens_m = qp.convert(ens_red, 'mixmod', xvals=xvals, ncomps=ncomps)`
to:
`ens_m = qp.convert(ens_red, 'mixmod', xvals=xvals, ncomps=ncomps, nsamples=100_000)` 

Note that `nsamples` defaults to 1000, in the `extract_mixmod_fit_samples` function. And 100_000 may be too large to be computationally tractable, but does start to converge. FWIW, using the default `n_sample=1000` with 10 iterations ran in about 0.2 seconds and using `n_sample=100_000` with 10 iterations ran in about 4.3 seconds. 

The other option that seems like a better choice would be to make a slight code change and pin `random_state` in the call to `rvs` in `extract_mixmod_fit_samples`. i.e. the call would be 
```
RANDOM_STATE = 42  # or your favorite number :)
samples = in_dist.rvs(size=n_sample, random_state=RANDOM_STATE)
```

This would not guarantee convergence, but would ensure reproducible fits with all other variables held constant. 

Below are some (hopefully) helpful examples. For all of these, I started with a predefined multi-modal (3 guassians in this case) mixmod Ensemble , and am focusing on the first peak in the mixmod. I use that as input to convert to another mixmod Ensemble. So yes, a contrived example, but drives the point home.  

The code to create the initial mixmod Ensemble:
```
mu = np.array([[0.0,1.1, 2.9], [0.5, 1.25, 2.8], [0.3, 1.9, 2.2]])
sig = np.array([[0.05,0.01,0.04], [0.05,0.01,0.02], [0.025, 0.01, 0.025]])
wt = np.array([[1,1,1], [1,1,1], [1,1,1]])
ens = qp.Ensemble(qp.mixmod, data=dict(means=mu, stds=sig, weights=wt))
```

### Baseline
Code:
```
xvals = np.linspace(0, 1., 301)
key=1
axes_m = ens.plot(key, xlim=(0,1.), label='Original', marker='.')

for i in range(10):
    ens_m = qp.convert(ens, 'mixmod', xvals=xvals, ncomps=3)
    _ = ens_m.plot(key, axes=axes_m, label=f'gaus_{i}', color=np.random.rand(3,))

leg_m = axes_m.legend()
```

![Image](https://user-images.githubusercontent.com/47493171/209389365-4ddf833b-a873-47b4-a81c-b360c4045b6a.png)
Note that the peaks are all over the place but generally align with the input.

### Larger number of samples
Code is same as above with this exception of the convert line:
```
ens_m = qp.convert(ens, 'mixmod', xvals=xvals, ncomps=3, nsamples=100_000)
```

![Image](https://user-images.githubusercontent.com/47493171/209389504-400c5964-5254-4178-93fe-0df446c8a4ca.png)
The peaks become more consistent, but there's still jitter between iterations.

### Pinning random_state
User code is the same as the baseline, `n_samples` is the default (1000). The change is in `conversion_funcs.py` as noted above.

![Image](https://user-images.githubusercontent.com/47493171/209389860-564d2e76-dceb-4306-8202-eb6a421fc81d.png)
All of the peaks align (the same values were produced for all iterations), but the number of samples isn't sufficient to reproduce the input peak (by eye anyway) 

And again, but this time setting `n_samples=100_000`.

![Image](https://user-images.githubusercontent.com/47493171/209390589-0c2a00bd-d625-43b9-aedf-e6b1dce17666.png)
Increasing the number of samples and pinning the random_state leads to consist peaks across iterations that reproduce the input peak fairly well (again, by eye).

**Comment by drewoldag** [comment]
I put together a quick PR that simply allows the user to pass a random_state when converting to a `mixmod` Ensemble, this way, at least you can get reproducible fits.
