### ISSUE TITLE
Conventions for flags for PDFs.

### ISSUE THREAD

**Issue by eacharles** [LSSTDESC/qp#98]
We should agree on conventions to flag PDF within an ensemble.

We can use the ancillary data to do this.  We just need to agree on some conventions and use them

**Comment by aimalz** [comment]
For completeness, this issue was inspired by LSSTDESC/RAIL/#78. While there is a `check_input` keyword option for making `qp.Ensemble` objects, it would be useful to flag the PDFs that really do require mathematical operations to be properly normalized, e.g. 'not_nonnegative`. That example in particular might also come with an addition to the `metadata` to specify the approach to normalize the flagged PDFs, since there are at least two obvious options, to set the negative values to 0 or adding a constant to the whole PDF so its minimum value is 0, before multiplying by a constant to ensure integration to 1 in either case.

**Comment by aimalz** [comment]
This isn't really actionable right now, so I'm closing the issue. We can continue discussing informally on Slack.
